/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import DAO.Connect;
import Models.UserModel;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author A D E P T
 */
public class LoginScreen extends javax.swing.JFrame {
    
    UserModel userModel = new UserModel();
    Connect connect = new Connect();
    
    public LoginScreen() {
        initComponents();
        connect.Connection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb_userPassword = new javax.swing.JLabel();
        txt_userName = new javax.swing.JTextField();
        lb_userName = new javax.swing.JLabel();
        txt_userPassword = new javax.swing.JPasswordField();
        bt_exit = new javax.swing.JButton();
        bt_enter = new javax.swing.JButton();
        lb_logScreen = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Locadora APS");
        setResizable(false);
        getContentPane().setLayout(null);

        lb_userPassword.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        lb_userPassword.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lb_userPassword.setText("Senha: ");
        getContentPane().add(lb_userPassword);
        lb_userPassword.setBounds(170, 190, 90, 25);

        txt_userName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_userNameActionPerformed(evt);
            }
        });
        getContentPane().add(txt_userName);
        txt_userName.setBounds(260, 140, 150, 23);

        lb_userName.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        lb_userName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lb_userName.setText("Usuário: ");
        getContentPane().add(lb_userName);
        lb_userName.setBounds(170, 140, 90, 25);

        txt_userPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_userPasswordActionPerformed(evt);
            }
        });
        getContentPane().add(txt_userPassword);
        txt_userPassword.setBounds(260, 190, 150, 23);

        bt_exit.setBackground(new java.awt.Color(255, 255, 255));
        bt_exit.setFont(new java.awt.Font("Calibri", 0, 15)); // NOI18N
        bt_exit.setText("Encerrar");
        bt_exit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        bt_exit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_exit.setMaximumSize(new java.awt.Dimension(91, 29));
        bt_exit.setMinimumSize(new java.awt.Dimension(91, 29));
        bt_exit.setPreferredSize(new java.awt.Dimension(91, 29));
        bt_exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_exitMouseClicked(evt);
            }
        });
        bt_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_exitActionPerformed(evt);
            }
        });
        getContentPane().add(bt_exit);
        bt_exit.setBounds(340, 250, 91, 29);

        bt_enter.setBackground(new java.awt.Color(255, 255, 255));
        bt_enter.setFont(new java.awt.Font("Calibri", 0, 15)); // NOI18N
        bt_enter.setText("Entrar");
        bt_enter.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        bt_enter.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_enter.setMaximumSize(new java.awt.Dimension(91, 29));
        bt_enter.setMinimumSize(new java.awt.Dimension(91, 29));
        bt_enter.setPreferredSize(new java.awt.Dimension(91, 29));
        bt_enter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_enterActionPerformed(evt);
            }
        });
        getContentPane().add(bt_enter);
        bt_enter.setBounds(230, 250, 91, 29);

        lb_logScreen.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        lb_logScreen.setForeground(new java.awt.Color(255, 255, 255));
        lb_logScreen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/LoginScreen.jpg"))); // NOI18N
        getContentPane().add(lb_logScreen);
        lb_logScreen.setBounds(0, 0, 620, 350);

        setSize(new java.awt.Dimension(636, 389));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_userPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_userPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_userPasswordActionPerformed

    private void bt_enterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_enterActionPerformed

        connect.executaSql("SELECT * FROM tb_users WHERE user_name='"+txt_userName.getText()+"'");
        try {
            connect.executaSql("SELECT * FROM tb_users WHERE user_name='"+txt_userName.getText()+"'");
            connect.rs.first();
            String strPass = new String(txt_userPassword.getPassword()).trim();
            if (connect.rs.getString("user_password").equals(strPass)) {
                MainScreen mainScreen = new MainScreen();
                mainScreen.setVisible(true);
                dispose();                
            } else {
                JOptionPane.showMessageDialog(rootPane, "Nome de usuário ou senha incorreto(s)!");
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Nome de usuário ou senha incorreto(s)!"+ex);
        }
        
    }//GEN-LAST:event_bt_enterActionPerformed

    private void bt_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_exitActionPerformed
        if (JOptionPane.showConfirmDialog(null,"Deseja encerrar o programa ?","Locadora APS",
        JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_bt_exitActionPerformed

    private void bt_exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_exitMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_exitMouseClicked

    private void txt_userNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_userNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_userNameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new LoginScreen().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_enter;
    private javax.swing.JButton bt_exit;
    private javax.swing.JLabel lb_logScreen;
    private javax.swing.JLabel lb_userName;
    private javax.swing.JLabel lb_userPassword;
    private javax.swing.JTextField txt_userName;
    private javax.swing.JPasswordField txt_userPassword;
    // End of variables declaration//GEN-END:variables
}
