/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import DAO.Connect;
import javax.swing.JOptionPane;

/**
 *
 * @author A D E P T
 */
public class MainScreen extends javax.swing.JFrame {

    UINewUser UINewUser = new UINewUser();
    UINewClient UINewClient = new UINewClient();
    UINewProduct UINewProduct = new UINewProduct();
    UIProductReports UIProductReports = new UIProductReports();
    UIClientReports UIClientReports = new UIClientReports();
    UINewRent UINewRent = new UINewRent();
    UIGiveBack UIGiveBack = new UIGiveBack();
    UIRentReports UIRentReports = new UIRentReports();
    Connect connect = new Connect();
    
    public MainScreen() {
        initComponents();
        connect.Connection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb_mainScreen = new javax.swing.JLabel();
        mn_main = new javax.swing.JMenuBar();
        mn_cadastros = new javax.swing.JMenu();
        mn_newClient = new javax.swing.JMenuItem();
        mn_newProduct = new javax.swing.JMenuItem();
        mn_NewUser = new javax.swing.JMenuItem();
        mn_rents = new javax.swing.JMenu();
        mn_give_back = new javax.swing.JMenu();
        mn_report = new javax.swing.JMenu();
        mn_rents_reports = new javax.swing.JMenuItem();
        mn_products = new javax.swing.JMenuItem();
        mn_clients = new javax.swing.JMenuItem();
        mn_tools = new javax.swing.JMenu();
        mn_welcome = new javax.swing.JMenuItem();
        mn_leave = new javax.swing.JMenu();
        mn_logout = new javax.swing.JMenuItem();
        mn_exit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(null);

        lb_mainScreen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Mscreen3.jpg"))); // NOI18N
        getContentPane().add(lb_mainScreen);
        lb_mainScreen.setBounds(0, 0, 1920, 1058);

        mn_cadastros.setText("Cadastros");

        mn_newClient.setText("Novo Cliente");
        mn_newClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mn_newClientActionPerformed(evt);
            }
        });
        mn_cadastros.add(mn_newClient);

        mn_newProduct.setText("Novo Produto");
        mn_newProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mn_newProductActionPerformed(evt);
            }
        });
        mn_cadastros.add(mn_newProduct);

        mn_NewUser.setText("Novo Usuário");
        mn_NewUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mn_NewUserActionPerformed(evt);
            }
        });
        mn_cadastros.add(mn_NewUser);

        mn_main.add(mn_cadastros);

        mn_rents.setText("Locação");
        mn_rents.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mn_rentsMouseClicked(evt);
            }
        });
        mn_rents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mn_rentsActionPerformed(evt);
            }
        });
        mn_main.add(mn_rents);

        mn_give_back.setText("Devoluções");
        mn_give_back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mn_give_backMouseClicked(evt);
            }
        });
        mn_give_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mn_give_backActionPerformed(evt);
            }
        });
        mn_main.add(mn_give_back);

        mn_report.setText("Relátorios");

        mn_rents_reports.setText("Locações");
        mn_rents_reports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mn_rents_reportsActionPerformed(evt);
            }
        });
        mn_report.add(mn_rents_reports);

        mn_products.setText("Produtos");
        mn_products.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mn_productsActionPerformed(evt);
            }
        });
        mn_report.add(mn_products);

        mn_clients.setText("Clientes");
        mn_clients.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mn_clientsActionPerformed(evt);
            }
        });
        mn_report.add(mn_clients);

        mn_main.add(mn_report);

        mn_tools.setText("Ferramentas");

        mn_welcome.setText("Bem-Vindo");
        mn_tools.add(mn_welcome);

        mn_main.add(mn_tools);

        mn_leave.setText("Sair");

        mn_logout.setText("Trocar de usuário");
        mn_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mn_logoutActionPerformed(evt);
            }
        });
        mn_leave.add(mn_logout);

        mn_exit.setText("Finalizar");
        mn_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mn_exitActionPerformed(evt);
            }
        });
        mn_leave.add(mn_exit);

        mn_main.add(mn_leave);

        setJMenuBar(mn_main);

        setSize(new java.awt.Dimension(1936, 1119));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mn_NewUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mn_NewUserActionPerformed
        connect.Connection();
        if (UINewUser==null) {
            
            UINewUser = new UINewUser();
            UINewUser.setVisible(true);
        } else {
            UINewUser.setVisible(true);
        }
    }//GEN-LAST:event_mn_NewUserActionPerformed

    private void mn_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mn_exitActionPerformed
        
        if (JOptionPane.showConfirmDialog(null,"Deseja encerrar o programa ?","Locadora APS",
        JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_mn_exitActionPerformed

    private void mn_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mn_logoutActionPerformed
        
        if (JOptionPane.showConfirmDialog(null,"Deseja retornar a tela de login ?","Locadora APS",
        JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION){
            LoginScreen loginScreen = new LoginScreen();
            loginScreen.setVisible(true);
            MainScreen.this.dispose();
        }
    }//GEN-LAST:event_mn_logoutActionPerformed

    private void mn_newClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mn_newClientActionPerformed
        connect.Connection();
        if (UINewClient==null) {
            
            UINewClient = new UINewClient();
            UINewClient.setVisible(true);
        } else {
            UINewClient.setVisible(true);
        }
    }//GEN-LAST:event_mn_newClientActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        int option = JOptionPane.showConfirmDialog(null, "Deseja finalizar o programa ?","Locadora APS",JOptionPane.YES_OPTION);
        
        if (option == JOptionPane.YES_OPTION) {
            connect.Disconnect();
            System.exit(0);
        }
    }//GEN-LAST:event_formWindowClosing

    private void mn_newProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mn_newProductActionPerformed
        connect.Connection();
        if (UINewProduct==null) {
            
            UINewProduct = new UINewProduct();
            UINewProduct.setVisible(true);
        } else {
            UINewProduct.setVisible(true);
        }
        
    }//GEN-LAST:event_mn_newProductActionPerformed

    private void mn_productsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mn_productsActionPerformed
        connect.Connection();
        if (UIProductReports==null) {
            
            UIProductReports = new UIProductReports();
            UIProductReports.setVisible(true);
        } else {
            UIProductReports.setVisible(true);
        }
    }//GEN-LAST:event_mn_productsActionPerformed

    private void mn_clientsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mn_clientsActionPerformed
        connect.Connection();
        if (UIClientReports==null) {
            
            UIClientReports = new UIClientReports();
            UIClientReports.setVisible(true);
        } else {
            UIClientReports.setVisible(true);
        }
    }//GEN-LAST:event_mn_clientsActionPerformed

    private void mn_rentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mn_rentsActionPerformed

    }//GEN-LAST:event_mn_rentsActionPerformed

    private void mn_give_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mn_give_backActionPerformed

    }//GEN-LAST:event_mn_give_backActionPerformed

    private void mn_rents_reportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mn_rents_reportsActionPerformed
        connect.Connection(); 
        if (UIRentReports==null) {            
            UIRentReports = new UIRentReports();
            UIRentReports.setVisible(true);
        } else {
            UIRentReports.setVisible(true);
        }
    }//GEN-LAST:event_mn_rents_reportsActionPerformed

    private void mn_rentsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mn_rentsMouseClicked
        connect.Connection();
        if (UINewRent==null) {
            
            UINewRent = new UINewRent();
            UINewRent.setVisible(true);
        } else {
            UINewRent.setVisible(true);
        }
    }//GEN-LAST:event_mn_rentsMouseClicked

    private void mn_give_backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mn_give_backMouseClicked
        connect.Connection();
        if (UIGiveBack==null) {            
            UIGiveBack = new UIGiveBack();
            UIGiveBack.setVisible(true);
        } else {
            UIGiveBack.setVisible(true);
        }
    }//GEN-LAST:event_mn_give_backMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new MainScreen().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lb_mainScreen;
    private javax.swing.JMenuItem mn_NewUser;
    private javax.swing.JMenu mn_cadastros;
    private javax.swing.JMenuItem mn_clients;
    private javax.swing.JMenuItem mn_exit;
    private javax.swing.JMenu mn_give_back;
    private javax.swing.JMenu mn_leave;
    private javax.swing.JMenuItem mn_logout;
    private javax.swing.JMenuBar mn_main;
    private javax.swing.JMenuItem mn_newClient;
    private javax.swing.JMenuItem mn_newProduct;
    private javax.swing.JMenuItem mn_products;
    private javax.swing.JMenu mn_rents;
    private javax.swing.JMenuItem mn_rents_reports;
    private javax.swing.JMenu mn_report;
    private javax.swing.JMenu mn_tools;
    private javax.swing.JMenuItem mn_welcome;
    // End of variables declaration//GEN-END:variables
}