/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import DAOModels.DAOUser;
import Models.UserModel;
import javax.swing.JOptionPane;

/**
 *
 * @author A D E P T
 */
public class UINewUser extends javax.swing.JFrame {
    
    UserModel userModel = new UserModel();
    DAOUser DAOUser = new DAOUser();
    
    public UINewUser() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lb_NewUserTitle = new javax.swing.JLabel();
        lb_userName = new javax.swing.JLabel();
        lb_userPassword = new javax.swing.JLabel();
        lb_confirmPassword = new javax.swing.JLabel();
        txt_userName = new javax.swing.JTextField();
        txt_userPassword = new javax.swing.JPasswordField();
        txt_confirmPassword = new javax.swing.JPasswordField();
        bt_register = new javax.swing.JButton();
        bt_cancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lb_NewUserTitle.setFont(new java.awt.Font("Calibri", 1, 30)); // NOI18N
        lb_NewUserTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_NewUserTitle.setText("Novo Usuário");

        lb_userName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lb_userName.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lb_userName.setText("Usuário: ");

        lb_userPassword.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lb_userPassword.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lb_userPassword.setText("Senha: ");

        lb_confirmPassword.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lb_confirmPassword.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lb_confirmPassword.setText("Confirmar Senha: ");

        bt_register.setBackground(new java.awt.Color(255, 255, 255));
        bt_register.setFont(new java.awt.Font("Calibri", 0, 15)); // NOI18N
        bt_register.setText("Cadastrar");
        bt_register.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        bt_register.setFocusPainted(false);
        bt_register.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_register.setMaximumSize(new java.awt.Dimension(90, 28));
        bt_register.setMinimumSize(new java.awt.Dimension(90, 28));
        bt_register.setPreferredSize(new java.awt.Dimension(90, 28));
        bt_register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_registerActionPerformed(evt);
            }
        });

        bt_cancel.setBackground(new java.awt.Color(255, 255, 255));
        bt_cancel.setFont(new java.awt.Font("Calibri", 0, 15)); // NOI18N
        bt_cancel.setText("Cancelar");
        bt_cancel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        bt_cancel.setFocusPainted(false);
        bt_cancel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_cancel.setMaximumSize(new java.awt.Dimension(90, 28));
        bt_cancel.setMinimumSize(new java.awt.Dimension(90, 28));
        bt_cancel.setPreferredSize(new java.awt.Dimension(90, 28));
        bt_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_cancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lb_NewUserTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(bt_register, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bt_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lb_confirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lb_userPassword, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lb_userName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txt_userPassword, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(txt_userName, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_confirmPassword))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lb_NewUserTitle)
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_userName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_userName))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_userPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_userPassword))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_confirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_confirmPassword))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_register, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(416, 339));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bt_registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_registerActionPerformed
        if(txt_userName.getText().isEmpty()) {
            
            JOptionPane.showMessageDialog(null, "Insira o nome de USUÁRIO para continuar!");
            txt_userName.requestFocus();
            
        } else if(txt_userPassword.getText().isEmpty()) {
            
            JOptionPane.showMessageDialog(null, "Insira uma SENHA para continuar!");
            txt_userPassword.requestFocus();
            
        } else if(txt_confirmPassword.getText().isEmpty()) {
            
            JOptionPane.showMessageDialog(null, "Preencha o campo CONFIRME SUA SENHA para continuar!");
            txt_confirmPassword.requestFocus();
            
        } else if(!txt_userPassword.getText().equals(txt_confirmPassword.getText())) {
            
            JOptionPane.showMessageDialog(null, "As senhas digitas não coincidem!");
            txt_userPassword.setText("");
            txt_confirmPassword.setText("");
            txt_userPassword.requestFocus();            
            
        } else {
              
            userModel.setUser_name(txt_userName.getText());
            userModel.setUser_password(txt_userPassword.getText());
            DAOUser.Salvar(userModel);
            txt_userName.setText("");
            txt_userPassword.setText("");
            txt_confirmPassword.setText("");
            dispose();
          }
    }//GEN-LAST:event_bt_registerActionPerformed

    private void bt_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_cancelActionPerformed

        if (JOptionPane.showConfirmDialog(null,"Deseja cancelar o cadastro ?","Novo Usuário",
        JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION) {
            
            txt_userName.setText("");
            txt_userPassword.setText("");
            txt_confirmPassword.setText("");
            dispose();
                        
        }
            
    }//GEN-LAST:event_bt_cancelActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        int option = JOptionPane.showConfirmDialog(null, "Deseja cancelar o cadastro ?","Novo Usuário",JOptionPane.YES_OPTION);
        
        if (option == JOptionPane.YES_OPTION) {
            dispose();
        }
        
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UINewUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UINewUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UINewUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UINewUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new UINewUser().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_cancel;
    private javax.swing.JButton bt_register;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lb_NewUserTitle;
    private javax.swing.JLabel lb_confirmPassword;
    private javax.swing.JLabel lb_userName;
    private javax.swing.JLabel lb_userPassword;
    private javax.swing.JPasswordField txt_confirmPassword;
    private javax.swing.JTextField txt_userName;
    private javax.swing.JPasswordField txt_userPassword;
    // End of variables declaration//GEN-END:variables
}
