/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import DAO.Connect;
import DAOModels.DAOProductReports;
import Models.ProductModel;
import javax.swing.JOptionPane;

/**
 *
 * @author A D E P T
 */
public class UINewProduct extends javax.swing.JFrame {

    ProductModel productModel = new ProductModel();
    DAOProductReports DAOProduct = new DAOProductReports();
    Connect connect = new Connect();
    
    public UINewProduct() {
        initComponents();
        connect.Connection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lb_title = new javax.swing.JLabel();
        lb_film_name = new javax.swing.JLabel();
        lb_gender = new javax.swing.JLabel();
        cb_gender = new javax.swing.JComboBox<>();
        txt_film_name = new javax.swing.JTextField();
        lb_synopsis = new javax.swing.JLabel();
        sp_synopsis = new javax.swing.JScrollPane();
        txt_synopsis = new javax.swing.JTextPane();
        bt_register = new javax.swing.JButton();
        bt_cancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lb_title.setFont(new java.awt.Font("Calibri", 1, 40)); // NOI18N
        lb_title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_title.setText("Cadastar Filme");

        lb_film_name.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lb_film_name.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lb_film_name.setText("Nome do Filme: ");

        lb_gender.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lb_gender.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lb_gender.setText("Gênero: ");

        cb_gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Escolher...", "Ação", "Aventura", "Comédia", "Terror", "Romance", "Drama" }));

        lb_synopsis.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lb_synopsis.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lb_synopsis.setText("Sinopse: ");

        txt_synopsis.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                txt_synopsisComponentAdded(evt);
            }
        });
        sp_synopsis.setViewportView(txt_synopsis);

        bt_register.setBackground(new java.awt.Color(255, 255, 255));
        bt_register.setFont(new java.awt.Font("Calibri", 0, 15)); // NOI18N
        bt_register.setText("Cadastrar");
        bt_register.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        bt_register.setFocusPainted(false);
        bt_register.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_register.setMaximumSize(new java.awt.Dimension(90, 28));
        bt_register.setMinimumSize(new java.awt.Dimension(90, 28));
        bt_register.setPreferredSize(new java.awt.Dimension(90, 28));
        bt_register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_registerActionPerformed(evt);
            }
        });

        bt_cancel.setBackground(new java.awt.Color(255, 255, 255));
        bt_cancel.setFont(new java.awt.Font("Calibri", 0, 15)); // NOI18N
        bt_cancel.setText("Cancelar");
        bt_cancel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        bt_cancel.setFocusPainted(false);
        bt_cancel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_cancel.setMaximumSize(new java.awt.Dimension(90, 28));
        bt_cancel.setMinimumSize(new java.awt.Dimension(90, 28));
        bt_cancel.setPreferredSize(new java.awt.Dimension(90, 28));
        bt_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_cancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lb_title, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lb_film_name, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_film_name, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lb_gender, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cb_gender, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lb_synopsis, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(bt_register, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bt_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(17, 17, 17))
                            .addComponent(sp_synopsis))))
                .addGap(0, 121, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lb_title)
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_film_name)
                    .addComponent(txt_film_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_gender)
                    .addComponent(cb_gender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_synopsis)
                    .addComponent(sp_synopsis, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_register, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(516, 439));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bt_registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_registerActionPerformed
        if(txt_film_name.getText().isEmpty()) {

            JOptionPane.showMessageDialog(null, "Preencha o nome do filme para continuar!");
            txt_film_name.requestFocus();

        } else if(cb_gender.getSelectedIndex()==0) {

            JOptionPane.showMessageDialog(null, "Selecione o gênero do filme para continuar!");
            cb_gender.requestFocus();

        } else if(txt_synopsis.getText().isEmpty()) {

            JOptionPane.showMessageDialog(null, "Adcione uma sinopse ao filme para continuar!");
            txt_synopsis.requestFocus();

        } else {

            productModel.setProduct_name(txt_film_name.getText());
            productModel.setProduct_gender((String) cb_gender.getSelectedItem());
            productModel.setProduct_synopsis(txt_synopsis.getText());
            DAOProduct.Salvar(productModel);
            txt_film_name.setText("");
            cb_gender.setSelectedIndex(0);
            txt_synopsis.setText("");
            connect.Disconnect();
            dispose();
        }
    }//GEN-LAST:event_bt_registerActionPerformed

    private void bt_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_cancelActionPerformed
       
        if (JOptionPane.showConfirmDialog(null,"Deseja cancelar o cadastro ?","Novo Produto",
        JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION) {
            
            txt_film_name.setText("");
            cb_gender.setSelectedIndex(0);
            txt_synopsis.setText("");            
            dispose();
        }
        
    }//GEN-LAST:event_bt_cancelActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing

        int option = JOptionPane.showConfirmDialog(null, "Deseja cancelar o cadastro ?","Novo Usuário",JOptionPane.YES_OPTION);

        if (option == JOptionPane.YES_OPTION) {
            dispose();
        }
    }//GEN-LAST:event_formWindowClosing

    private void txt_synopsisComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_txt_synopsisComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_synopsisComponentAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UINewProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UINewProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UINewProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UINewProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UINewProduct().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_cancel;
    private javax.swing.JButton bt_register;
    private javax.swing.JComboBox<String> cb_gender;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lb_film_name;
    private javax.swing.JLabel lb_gender;
    private javax.swing.JLabel lb_synopsis;
    private javax.swing.JLabel lb_title;
    private javax.swing.JScrollPane sp_synopsis;
    private javax.swing.JTextField txt_film_name;
    private javax.swing.JTextPane txt_synopsis;
    // End of variables declaration//GEN-END:variables
}
