/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import DAO.Connect;
import DAOModels.DAORent;
import Models.RentModel;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author A D E P T
 */
public class UINewRent extends javax.swing.JFrame {

    Connect connect = new Connect();
    RentModel rentModel = new RentModel();
    DAORent DAORent = new DAORent();
    
    public UINewRent() {
        initComponents();
        completeClientName();
        completeProductName();
        connect.Connection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    public void completeClientName(){
        connect.Connection();
        
        connect.executaSql("SELECT * FROM tb_clients ORDER BY client_name");
        try {
            connect.rs.first();
            cb_client_name.removeAllItems();
            do {
                cb_client_name.addItem(connect.rs.getString("client_name"));
            } while (connect.rs.next());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane,"Erro ao preencher clientes: "+ ex);
        }
    }
    
    public void completeProductName(){
        connect.Connection();
        
        connect.executaSql("SELECT * FROM tb_products ORDER BY product_name");
        try {
            connect.rs.first();
            cb_product_name.removeAllItems();
            do {
                cb_product_name.addItem(connect.rs.getString("product_name"));
            } while (connect.rs.next());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane,"Erro ao preencher filmes: "+ ex);
        }
    }
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lb_location_title = new javax.swing.JLabel();
        lb_client_name = new javax.swing.JLabel();
        cb_client_name = new javax.swing.JComboBox<>();
        lb_product_name = new javax.swing.JLabel();
        cb_product_name = new javax.swing.JComboBox<>();
        lb_rent_date = new javax.swing.JLabel();
        lb_rent_delivery_date = new javax.swing.JLabel();
        txt_rent_date = new javax.swing.JTextField();
        txt_rent_delivery_date = new javax.swing.JTextField();
        bt_rent = new javax.swing.JButton();
        bt_cancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lb_location_title.setFont(new java.awt.Font("Calibri", 1, 50)); // NOI18N
        lb_location_title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_location_title.setText("Locar Filme");

        lb_client_name.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lb_client_name.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lb_client_name.setText("Nome do Cliente: ");

        cb_client_name.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione o cliente" }));
        cb_client_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_client_nameActionPerformed(evt);
            }
        });

        lb_product_name.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lb_product_name.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lb_product_name.setText("Nome do Filme: ");

        cb_product_name.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione o filme" }));

        lb_rent_date.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lb_rent_date.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lb_rent_date.setText("Data de Locação: ");

        lb_rent_delivery_date.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lb_rent_delivery_date.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lb_rent_delivery_date.setText("Data para Devolução: ");

        bt_rent.setBackground(new java.awt.Color(255, 255, 255));
        bt_rent.setFont(new java.awt.Font("Calibri", 0, 15)); // NOI18N
        bt_rent.setText("Locar");
        bt_rent.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        bt_rent.setFocusPainted(false);
        bt_rent.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_rent.setMaximumSize(new java.awt.Dimension(90, 28));
        bt_rent.setMinimumSize(new java.awt.Dimension(90, 28));
        bt_rent.setPreferredSize(new java.awt.Dimension(90, 28));
        bt_rent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_rentActionPerformed(evt);
            }
        });

        bt_cancel.setBackground(new java.awt.Color(255, 255, 255));
        bt_cancel.setFont(new java.awt.Font("Calibri", 0, 15)); // NOI18N
        bt_cancel.setText("Cancelar");
        bt_cancel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        bt_cancel.setFocusPainted(false);
        bt_cancel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_cancel.setMaximumSize(new java.awt.Dimension(90, 28));
        bt_cancel.setMinimumSize(new java.awt.Dimension(90, 28));
        bt_cancel.setPreferredSize(new java.awt.Dimension(90, 28));
        bt_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_cancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lb_location_title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(316, 316, 316)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lb_rent_delivery_date, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lb_rent_date, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lb_product_name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lb_client_name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(bt_rent, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bt_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cb_client_name, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_product_name, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_rent_date, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_rent_delivery_date, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(440, 440, 440))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(lb_location_title)
                .addGap(92, 92, 92)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_client_name)
                    .addComponent(cb_client_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lb_product_name)
                    .addComponent(cb_product_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_rent_date)
                    .addComponent(txt_rent_date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lb_rent_delivery_date)
                    .addComponent(txt_rent_delivery_date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(89, 89, 89)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_rent, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(112, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1276, 689));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bt_rentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_rentActionPerformed
       if (txt_rent_date.getText().isEmpty()) {

            JOptionPane.showMessageDialog(null, "Insira a data de locação para continuar!");
            txt_rent_date.requestFocus();

        } else if (txt_rent_delivery_date.getText().isEmpty()) {

            JOptionPane.showMessageDialog(null, "Insira a data de devolução para continuar!");
            txt_rent_delivery_date.requestFocus();

        } else {

            rentModel.setClient_name((String) cb_client_name.getSelectedItem());
            rentModel.setProduct_name((String) cb_product_name.getSelectedItem());
            rentModel.setRent_date(txt_rent_date.getText());
            rentModel.setRent_delivery_date(txt_rent_delivery_date.getText());
            DAORent.Salvar(rentModel);
            cb_client_name.setSelectedIndex(0);
            cb_product_name.setSelectedIndex(0);
            txt_rent_date.setText("");
            txt_rent_delivery_date.setText("");
            dispose();
            connect.Disconnect();
            
        }
    }//GEN-LAST:event_bt_rentActionPerformed

    private void bt_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_cancelActionPerformed
        int option = JOptionPane.showConfirmDialog(null, "Deseja cancelar a locação do produto ?","Locar",JOptionPane.YES_OPTION);
        
        if (option == JOptionPane.YES_OPTION) {
            dispose();
        }
    }//GEN-LAST:event_bt_cancelActionPerformed

    private void cb_client_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_client_nameActionPerformed
        
        
        
    }//GEN-LAST:event_cb_client_nameActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        int option = JOptionPane.showConfirmDialog(null, "Deseja cancelar a locação do produto ?","Locar",JOptionPane.YES_OPTION);
        
        if (option == JOptionPane.YES_OPTION) {
            dispose();
        }
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UINewRent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UINewRent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UINewRent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UINewRent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UINewRent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_cancel;
    private javax.swing.JButton bt_rent;
    private javax.swing.JComboBox<String> cb_client_name;
    private javax.swing.JComboBox<String> cb_product_name;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lb_client_name;
    private javax.swing.JLabel lb_location_title;
    private javax.swing.JLabel lb_product_name;
    private javax.swing.JLabel lb_rent_date;
    private javax.swing.JLabel lb_rent_delivery_date;
    private javax.swing.JTextField txt_rent_date;
    private javax.swing.JTextField txt_rent_delivery_date;
    // End of variables declaration//GEN-END:variables
}
